name: my_plugin
author: Unknown
email: nobody@nowhere.com
url: http://example.com
version: '0.1'
title: 'my_plugin'
icon: question
# dependency on Core is required for UI plugins
dependencies:
    - !PluginDependency {
        plugin_name: core
    }
    # - !OptionalPluginDependency {
    #   plugin_name: my_other_plugin
    # }
    # - !ModuleDependency {
    #   module_name: requests
    # }
    # - !BinaryDependency {
    #   binary_name: curl
    # }
resources:
    - 'resources/js/module.es'
    - 'resources/js/routing.es'
    - 'resources/js/controllers/index.controller.es'
    - 'resources/partial/index.html'
    - 'ng:example.my_plugin'
    # - 'ng:my.plugin.angular-submodule'
    # - 'resources/module.js'
    # - 'resources/module.coffee'
    # - 'resources/styles.css'
    # - 'resources/styles.less'
